# Generated by Django 5.0.3 on 2024-04-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_title', models.CharField(max_length=255, unique=True)),
                ('shop_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'shops',
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, unique=True)),
                ('product_description', models.CharField(max_length=255)),
                ('product_amount', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_images', models.ImageField(upload_to='')),
                ('product_active', models.BooleanField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
